title = "Restore Internet Color"
version = "1.1.0"
authors = [ "Prof. 9" ]
unsafe = true
url = "https://forums.therockmanexezone.com/mmbnlc-pc-restore-internet-color-mod-exe3-t16764.html"
requires_loader_version = ">=0.11.0"
requires_game = ["Vol1"]
